version: '3.8'

services:
  
  app:
    build: g_drive
      # context: ./g_drive
    restart: always
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
